### ISSUE TITLE
Bots

### ISSUE THREAD

**Issue by kwurst** [LibreFoodPantry/ProjectTemplate#11]
Another related item...

As I understand it, [Probot](https://probot.github.io/) is a framework for developing bots for github that can be connected to projects to perform automated tasks. There are several very useful bots already implemented that I would like to take advantage of. So two questions...

* Is there an equivalent to Probot in the GitLab community that allows for the creation of more automated tools? Even if we don't create them, we could benefit from tools created by others in the future.
* Is there functionality in GitLab that is equivalent to the more popular existing Probot bots?

_Originally posted by @StoneyJackson in https://github.com/LibreFoodPantry/Community/issues/37#issuecomment-509696852_

**Comment by StoneyJackson** [comment]
I don't think this is an issue for me anymore. Whichever we go with there will be some form of bots. How difficult they are is another story. Anyway, I'm over it for now :) So I'm closing.
