### ISSUE TITLE
Redesign CONTRIBUTING so it has less reasons to change

### ISSUE THREAD

**Issue by StoneyJackson** [LibreFoodPantry/ProjectTemplate#13]
CONTRIBUTING.adoc is the entry point for developers wanting to contribute to this project. It is a standard file with a standard name (CONTRIBUTING.*) and location (the root of the project). A project will have project specific developer documentation (e.g., how to run the automated tests) and project independent developer documentation (e.g., LFP workflow, etc.). With this in mind, we should design CONTRIBUTING.adoc so that it only has one reason to change. Right now it has too many reasons to change. This is going to cause conflicts when we update the project independent documentation.

So I propose the following:

* CONTRIBUTING.adoc - Contains important links to other documentation that will not change (LICENSE, DCO, etc.), including a link to a project specific documentation file (maybe docs/dev/project-specific.md).
* Moving workflow stuff to docs/dev/workflow/ .

**Comment by kwurst** [comment]
Single Responsibility Principle FTW!

**Comment by StoneyJackson** [comment]
In that pr I think I may have backtracked on my previous intention. I instead favored an overview of most topics with links to more details.
