### ISSUE TITLE
Fix broken embedded diagram images for shop setup documentation

### ISSUE THREAD

**Issue by cradkowski** [LibreFoodPantry/ProjectTemplate#19]
After merging the shop-setup-documentation branch into master the links to the raw image files for the diagrams went away, resulting in a 404 error if you click on the image files within the shop setup markdown documents. 

Example: https://raw.githubusercontent.com/LibreFoodPantry/ProjectTemplate/shop_setup_documentation/docs/dev/shop-setup/diagrams/GitHub_Setup_Shop_Board.png

It looks like if you are going to have images embedded within markdown documents the source for these images needs to be the final location where the image files will be located in a repository when merged into the master branch so it doesn't break after it is merged and the branch is deleted.

This needs to be fixed on all of the shop setup documents.

**Comment by StoneyJackson** [comment]
I think making them relative works....

For example `![GitHub Shop Board Diagram](diagrams/GitHub_Setup_Shop_Board.png)`

**Comment by cradkowski** [comment]
Fixed issue: 
https://github.com/LibreFoodPantry/ProjectTemplate/pull/21
