### ISSUE TITLE
Document links broken

### ISSUE THREAD

**Issue by cradkowski** [LibreFoodPantry/ProjectTemplate#22]
Converting the various documents from .adoc to .md (https://github.com/LibreFoodPantry/ProjectTemplate/pull/20) has caused documents that previously linked to the old .adoc format to result in a missing link now.

All documents that reference the old .adoc format or mention it need to be updated to use the new .md documents.

**Comment by StoneyJackson** [comment]
Good catch!

**Comment by cradkowski** [comment]
https://github.com/LibreFoodPantry/ProjectTemplate/pull/24
