### ISSUE TITLE
Shop workflow documentation

### ISSUE THREAD

**Issue by kwurst** [LibreFoodPantry/ProjectTemplate#8]
Complete first draft of documentation for shop workflow. Make it as platform agnostic as possible (we'll aim for choosing a platform on 6 August 2019.)

Upload draft documentation to Template-Project.

**Comment by StoneyJackson** [comment]
Let's do this... I'm going to close this issue since we have an initial shop workflow documented. Instead, I'll open separate issues for things like diagrams and such. Give me a few minutes.

**Comment by cradkowski** [comment]
I'm deleting the branch I created for this
https://github.com/LibreFoodPantry/ProjectTemplate/tree/shop_workflow_documentation
